name: CI

on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps: 
      - uses:   actions/checkout@v4
      - name:   install Node
        uses:   actions/setup-node@v3
        with:
          node-version: '18'
      - run: make setup

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses:   actions/checkout@v4
      - run: make lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses:   actions/checkout@v4
      - run: make test
  hexlet:
    runs-on: ubuntu-latest
    steps:
      - uses: hexlet-components/hello-from-hexlet-action@release


